### PR TITLE
[COREV] Fix the encoding of mem instructions 

### PR DESCRIPTION
**Pull request by ChunyuLiao**
The original encoding of this instruction set extension was based on CV32E40P version 1.  The encoding provided by this patch is based on the instruction encoding of CV32E40P version 2.  See [this spreasheet of instruction encodings](https://github.com/openhwgroup/cv32e40p/files/9949531/pulp_encoding_blocks-OPHW-2022-10-07.xlsx), which are now in the [official documentation of instruction set extensions](https://github.com/openhwgroup/cv32e40p/blob/master/docs/source/instruction_set_extensions.rst)

### CODE REVIEW

**Comment by CharKeaney** [comment]
Looks generally sensible at first inspection, although the commit does need a proper title and description detailing what instruction encodings have been changed and why.

**Comment by CharKeaney** [comment]
> Looks generally sensible at first inspection, although the commit does need a proper title and description detailing what instruction encodings have been changed and why.

Upon further inspection it looks like all of the encoding changes are correct so functionally the patch looks good.

**Comment by jeremybennett** [comment]
The initial description comment needs to be included in the commit message of the one commit as a description.  Then this commit is good to merge.

**Comment by ChunyuLiao** [comment]
Updated the description information of the commit message:
https://github.com/ChunyuLiao/corev-llvm-project/commit/1d56a2bd5c652bf79cefe39fb6e9f2d17996f13a

**Comment by jeremybennett** [comment]
With this change, the patch is good to merge.

**Comment by jeremybennett** [comment]
Thank you for the change. This is now good to merge.

**Pull request merged**
