### PR TITLE
[RISCV] Backport patch D153721

### PR DESCRIPTION
**Pull request by melonedo**
This commit minimally adapts and backports change from https://reviews.llvm.org/D153721:
- The format of cv.avgu/srl/sra/sll/or/xor/and is changed;
- The extension name changed to `Xcvsimd`;
- Old test files are replaced with `XCVsimd{-invalid}.s`

Note that cv.srl/sra/sll still has an issue openhwgroup/corev-binutils-gdb#104

### CODE REVIEW

**Comment by PaoloS02** [comment]
Looks good, although I find a minor conflict when I try to rebase this on top of the current development branch. Could you please rebase your branch and fix that?

**Comment by PaoloS02** [comment]
I cloned this branch ad tried to rebase it on the latest version of the original development branch and I see there are several conflicts. It could be more practical to cherry-pick the branch on top of a fresh copy of the development branch

**Comment by ChunyuLiao** [comment]
funan back to school , I think we can close this.

**Comment by PaoloS02** [comment]
New pull request to merge this: #85

**Pull request closed without merging**
