### PR TITLE
Roll forward repository to upstream LLVM as of 25 Oct 2022.

### PR DESCRIPTION
**Pull request by CharKeaney**
This patch contains the original corev-llvm development branch, rebased on upstream llvm. Where merge conflicts have occurred they have been resolved. Where upstream changes have broken previous functionality, this has been repaired.

### CODE REVIEW

**Comment by jeremybennett** [comment]
@ChunyuLiao Would you be able to act as a reviewer for this project. Thanks

**Comment by ChunyuLiao** [comment]
image
At the moment it looks like there might be a conflict.

I'm compiling the CharKeaney‘s code locally, I'll update when I have the results

**Comment by ChunyuLiao** [comment]
LGTM if there are no conflicts

**Comment by jeremybennett** [comment]
This is good to merge. Conflicts are due to rebasing on upstream so this will be a force push.

**Pull request merged**
