### PR TITLE
Fixed signedness of simd shuffle and simd avgu

### PR DESCRIPTION
**Pull request by adeel10x**
The 6-bit immediate operand of cv.shuffle.sci.b, cv.avgu.sci.b, and cv.avgu.sci.h was changed from signed to unsigned, to make implementation consistent with the spec.

### CODE REVIEW

**Comment by Tameem-10xE** [comment]
All tests related to Shuffle SIMD and AVG will pass,
image

**Comment by ChunyuLiao** [comment]
the CI fail, https://github.com/openhwgroup/corev-llvm-project/actions/runs/6822593006/job/18792376249?pr=87
image

**Comment by adeel10x** [comment]
@Tameem-10xE has updated the repo. Tests can be run now.

**Comment by adeel10x** [comment]
These mac-OS tests are failing for multiple Pull Requests.
image

**Comment by PaoloS02** [comment]
The changes for avgu were already included with a back ported commit. The fix for the shuffle instruction has been merged with #100 . This can now be closed.

**Pull request closed without merging**
